name: Continuous Integration

on: [push, pull_request]

env:
  pnpm-version: 8
  node-version: 20

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: ${{ env.pnpm-version }}
          run_install: true

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: "pnpm"

      - run: pnpm run lint

  unit:
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: ${{ env.pnpm-version }}
          run_install: true

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: "pnpm"

      - run: pnpm run test:unit
        working-directory: ./packages/solid-apg
