name: Publish solid-apg
run-name: solid-apg@${{ github.ref_name }}

on:
  release:
    types: [published]

env:
  pnpm-version: 8
  node-version: 18

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: solid-apg
      url: https://npmjs.com/package/solid-apg

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.pnpm-version }}
          run_install: true

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}

      - run: npm publish
        working-directory: ./packages/solid-apg
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
