name: Publish solid-apg
run-name: solid-apg@${{ github.ref_name }}

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: solid-apg
      url: https://npmjs.com/package/solid-apg

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - run: npm publish --access public
        working-directory: ./packages/solid-apg
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
